title: "METADATA Foundation"
description: ""
lang: "ru_RU"
logo: ""
image: ""

sass:
  style: compressed
  sass_dir: assets/css/

twitter:
  username: "metadatafdn"
  card: "summary"

social:
  name: "METADATA Foundation"
  links:
  - https://twitter.com/metadatafdn
  - https://vk.com/metadatafdn

author:
  name: "METADATA Foundation"
  email: "kitsune.solar@gmail.com"
  github: "KitsuneSolar"
  twitter: "KitsuneSolar"

plugins:
- jekyll-seo-tag
- jekyll-sitemap
